### ISSUE TITLE
The extension does not appear in Forge

### ISSUE THREAD

**Issue by studiokevinabanto** [jhj0517/AdvancedLivePortrait-WebUI#22]
**I recently installed the extension, but the tab does not appear**

![imagen](https://github.com/user-attachments/assets/85527b41-8bb1-427b-89cc-5dc92db65545)

(venv) C:\stable-diffusion-webui-forge>python launch.py --xformers --cuda-malloc --skip-install
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-630-g85a7db3c
Commit hash: 85a7db3c0f076d186e630763139d082d31609dc0
Launching Web UI with arguments: --xformers --cuda-malloc --skip-install
Using cudaMallocAsync backend.
Total VRAM 8187 MB, total RAM 16334 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Using xformers cross attention
Using xformers attention for VAE
ControlNet preprocessor location: C:\stable-diffusion-webui-forge\models\ControlNetPreprocessor
16:36:58 - ReActor - STATUS - Running v0.7.1-b2 on Device: CUDA
Loading additional modules ... done.
2024-12-07 16:37:22,511 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'C:\\stable-diffusion-webui-forge\\models\\Stable-diffusion\\flux1-dev-Q4_0.gguf', 'hash': '3f6d9145'}, 'additional_modules': ['C:\\stable-diffusion-webui-forge\\models\\VAE\\ae.safetensors', 'C:\\stable-diffusion-webui-forge\\models\\text_encoder\\clip_l.safetensors', 'C:\\stable-diffusion-webui-forge\\models\\text_encoder\\t5-v1_1-xxl-encoder-Q4_K_M.gguf'], 'unet_storage_dtype': None}
Using online LoRAs in FP16: True
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 47.3s (prepare environment: 3.3s, launcher: 0.7s, import torch: 10.3s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 4.0s, initialize google blockly: 22.3s, create ui: 3.8s, gradio launch: 2.2s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 87.49% GPU memory (7163.00 MB) to load weights, and use 12.51% GPU memory (1024.00 MB) to do matrix computation.
Model selected: {'checkpoint_info': {'filename': 'C:\\stable-diffusion-webui-forge\\models\\Stable-diffusion\\flux1-dev-Q4_0.gguf', 'hash': '3f6d9145'}, 'additional_modules': ['C:\\stable-diffusion-webui-forge\\models\\VAE\\ae.safetensors', 'C:\\stable-diffusion-webui-forge\\models\\text_encoder\\clip_l.safetensors', 'C:\\stable-diffusion-webui-forge\\models\\text_encoder\\t5-v1_1-xxl-encoder-Q4_K_M.gguf'], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Model selected: {'checkpoint_info': {'filename': 'C:\\stable-diffusion-webui-forge\\models\\Stable-diffusion\\flux1-dev-Q4_0.gguf', 'hash': '3f6d9145'}, 'additional_modules': ['C:\\stable-diffusion-webui-forge\\models\\VAE\\ae.safetensors', 'C:\\stable-diffusion-webui-forge\\models\\text_encoder\\clip_l.safetensors', 'C:\\stable-diffusion-webui-forge\\models\\text_encoder\\t5-v1_1-xxl-encoder-Q4_K_M.gguf'], 'unet_storage_dtype': None}
Using online LoRAs in FP16: True

**Comment by jhj0517** [comment]
Hi @studiokevinabanto! 

Just to be sure, this is another dedicated `gradio` Web UI, not an extension.
If you want to run it as an extension to the forge, you should use  [sd-webui-AdvancedLivePortrait](https://github.com/jhj0517/sd-webui-AdvancedLivePortrait).

Did you install it from there?

**Comment by jhj0517** [comment]
OK, I just tried to reproduce with [sd-webui-AdvancedLivePortrait](https://github.com/jhj0517/sd-webui-AdvancedLivePortrait),

And I got permission error while installing requirements. 

The issue has been moved to https://github.com/jhj0517/sd-webui-AdvancedLivePortrait/issues/11, please continue there!
